### ISSUE TITLE
can LLM access starcraft2 ingame?

### ISSUE THREAD

**Issue by histmeisah** [manuelseeger/sc2-ai-coach#8]
AI Coach is a great implement by using gpt4. 
But when we play ladder game, can we using get the realtime information?
My work is LLM PLAY SC2 ,using botai code to realize similar function, but i dont know how can we access the real starcraft2 game during ladder game.

**Comment by manuelseeger** [comment]
No, you cannot access game state during a ladder game. That would be considered cheating, and is not the scope of my project. I am aiming to build an assistant ("coach") that helps a human ladder player with information outside of live gameplay.

**Comment by Kaszanas** [comment]
@histmeisah @manuelseeger technically it is possible.

Use a Python script with FFMPEG grabbing the screen, run computer vision on that (UI placement doesn't change), and you can monitor all the information that the player has access to. Could be useful for post-game screen recordings though. Spice it up with the parsed in-game replay data and you have something cool.

But that indeed could be considered cheating because you'd have an unfair advantage and EULA explicitly prohibits that.
You could probably use it in custom games when training with your friends.

As for LLM playing against humans @histmeisah you should be able to define a script where the agent plays against a person. But your participants would have to be able to run it on their machines.

**Comment by manuelseeger** [comment]
Closing this; Getting game state during ladder match is out of scope for this project.
